package thierry.cryptoprice.coingeckorepository.random

import thierry.cryptoprice.coingeckorepository.BitcoinPriceResponse
import thierry.cryptoprice.coingeckorepository.CurrencyPrices
import thierry.cryptoprice.coingeckorepository.MarketData
import kotlin.random.Random

internal fun Random.nextBitcoinPriceResponse() = BitcoinPriceResponse(
    id = "",
    marketData = MarketData(
        currencyPrices =
        CurrencyPrices(
            eur = 1.0,
            usd = 1.0,
            aud = 1.0,
            cad = 1.0,
            chf = 1.0,
            eth = 1.0,
            gbp = 1.0,
            jpy = 1.0,
            mxn = 1.0,
            pln = 1.0,
            rub = 1.0,
            xag = 1.0,
            xau = 1.0,
            zar = 1.0,
        ),
        high24h = CurrencyPrices(
            eur = 1.0,
            usd = 1.0,
            aud = 1.0,
            cad = 1.0,
            chf = 1.0,
            eth = 1.0,
            gbp = 1.0,
            jpy = 1.0,
            mxn = 1.0,
            pln = 1.0,
            rub = 1.0,
            xag = 1.0,
            xau = 1.0,
            zar = 1.0,
        ),
        low24h = CurrencyPrices(
            eur = 1.0,
            usd = 1.0,
            aud = 1.0,
            cad = 1.0,
            chf = 1.0,
            eth = 1.0,
            gbp = 1.0,
            jpy = 1.0,
            mxn = 1.0,
            pln = 1.0,
            rub = 1.0,
            xag = 1.0,
            xau = 1.0,
            zar = 1.0,
        ),
        ath = CurrencyPrices(
            eur = 1.0,
            usd = 1.0,
            aud = 1.0,
            cad = 1.0,
            chf = 1.0,
            eth = 1.0,
            gbp = 1.0,
            jpy = 1.0,
            mxn = 1.0,
            pln = 1.0,
            rub = 1.0,
            xag = 1.0,
            xau = 1.0,
            zar = 1.0,
        ),
        priceChangePercentage1hInCurrency = CurrencyPrices(
            eur = 1.0,
            usd = 1.0,
            aud = 1.0,
            cad = 1.0,
            chf = 1.0,
            eth = 1.0,
            gbp = 1.0,
            jpy = 1.0,
            mxn = 1.0,
            pln = 1.0,
            rub = 1.0,
            xag = 1.0,
            xau = 1.0,
            zar = 1.0,
        ),
        priceChangePercentage24hInCurrency = CurrencyPrices(
            eur = 1.0,
            usd = 1.0,
            aud = 1.0,
            cad = 1.0,
            chf = 1.0,
            eth = 1.0,
            gbp = 1.0,
            jpy = 1.0,
            mxn = 1.0,
            pln = 1.0,
            rub = 1.0,
            xag = 1.0,
            xau = 1.0,
            zar = 1.0,
        ),
        priceChangePercentage7dInCurrency = CurrencyPrices(
            eur = 1.0,
            usd = 1.0,
            aud = 1.0,
            cad = 1.0,
            chf = 1.0,
            eth = 1.0,
            gbp = 1.0,
            jpy = 1.0,
            mxn = 1.0,
            pln = 1.0,
            rub = 1.0,
            xag = 1.0,
            xau = 1.0,
            zar = 1.0,
        ),
        priceChangePercentage14dInCurrency = CurrencyPrices(
            eur = 1.0,
            usd = 1.0,
            aud = 1.0,
            cad = 1.0,
            chf = 1.0,
            eth = 1.0,
            gbp = 1.0,
            jpy = 1.0,
            mxn = 1.0,
            pln = 1.0,
            rub = 1.0,
            xag = 1.0,
            xau = 1.0,
            zar = 1.0,
        ),
        priceChangePercentage30dInCurrency = CurrencyPrices(
            eur = 1.0,
            usd = 1.0,
            aud = 1.0,
            cad = 1.0,
            chf = 1.0,
            eth = 1.0,
            gbp = 1.0,
            jpy = 1.0,
            mxn = 1.0,
            pln = 1.0,
            rub = 1.0,
            xag = 1.0,
            xau = 1.0,
            zar = 1.0,
        ),
        priceChangePercentage60dInCurrency = CurrencyPrices(
            eur = 1.0,
            usd = 1.0,
            aud = 1.0,
            cad = 1.0,
            chf = 1.0,
            eth = 1.0,
            gbp = 1.0,
            jpy = 1.0,
            mxn = 1.0,
            pln = 1.0,
            rub = 1.0,
            xag = 1.0,
            xau = 1.0,
            zar = 1.0,
        ),
        priceChangePercentage200dInCurrency = CurrencyPrices(
            eur = 1.0,
            usd = 1.0,
            aud = 1.0,
            cad = 1.0,
            chf = 1.0,
            eth = 1.0,
            gbp = 1.0,
            jpy = 1.0,
            mxn = 1.0,
            pln = 1.0,
            rub = 1.0,
            xag = 1.0,
            xau = 1.0,
            zar = 1.0,
        ),
        priceChangePercentage1yInCurrency = CurrencyPrices(
            eur = 1.0,
            usd = 1.0,
            aud = 1.0,
            cad = 1.0,
            chf = 1.0,
            eth = 1.0,
            gbp = 1.0,
            jpy = 1.0,
            mxn = 1.0,
            pln = 1.0,
            rub = 1.0,
            xag = 1.0,
            xau = 1.0,
            zar = 1.0,
        ),
        marketCapChangePercentage24hInCurrency = CurrencyPrices(
            eur = 1.0,
            usd = 1.0,
            aud = 1.0,
            cad = 1.0,
            chf = 1.0,
            eth = 1.0,
            gbp = 1.0,
            jpy = 1.0,
            mxn = 1.0,
            pln = 1.0,
            rub = 1.0,
            xag = 1.0,
            xau = 1.0,
            zar = 1.0,
        ),
        maxSupply = 20.999,
        circulatingSupply = 19.8,
    ),
    name = "", symbol = "",
)