package thierry.cryptoprice.coingeckorepository.mapper

import thierry.cryptoprice.coingeckorepository.BitcoinPriceResponse
import thierry.cryptoprice.coingeckorepository.MarketData
import thierry.cryptoprice.getbitcoinpriceusecase.model.BitcoinPrice
import thierry.cryptoprice.getbitcoinpriceusecase.model.CurrencyPrices
import thierry.cryptoprice.getbitcoinpriceusecase.model.MarketData as MarketDataFromUc

internal fun BitcoinPriceResponse.toBitcoinPrice(): BitcoinPrice = BitcoinPrice(
    id = id,
    marketData = marketData.toMarketDataUc(),
    name = name,
    symbol = symbol,
)

internal fun MarketData.toMarketDataUc(): MarketDataFromUc =
    MarketDataFromUc(
        currencyPrices = CurrencyPrices(
            eur = currencyPrices.eur,
            usd = currencyPrices.usd,
            aud = currencyPrices.aud,
            cad = currencyPrices.cad,
            chf = currencyPrices.chf,
            eth = currencyPrices.eth,
            gbp = currencyPrices.gbp,
            jpy = currencyPrices.jpy,
            mxn = currencyPrices.mxn,
            pln = currencyPrices.pln,
            rub = currencyPrices.rub,
            xag = currencyPrices.xag,
            xau = currencyPrices.xau,
            zar = currencyPrices.zar,
        ),
        high24h = CurrencyPrices(
            eur = high24h.eur,
            usd = high24h.usd,
            aud = high24h.aud,
            cad = high24h.cad,
            chf = high24h.chf,
            eth = high24h.eth,
            gbp = high24h.gbp,
            jpy = high24h.jpy,
            mxn = high24h.mxn,
            pln = high24h.pln,
            rub = high24h.rub,
            xag = high24h.xag,
            xau = high24h.xau,
            zar = high24h.zar,
        ),
        low24h = CurrencyPrices(
            eur = low24h.eur,
            usd = low24h.usd,
            aud = low24h.aud,
            cad = low24h.cad,
            chf = low24h.chf,
            eth = low24h.eth,
            gbp = low24h.gbp,
            jpy = low24h.jpy,
            mxn = low24h.mxn,
            pln = low24h.pln,
            rub = low24h.rub,
            xag = low24h.xag,
            xau = low24h.xau,
            zar = low24h.zar,
        ),
        ath = CurrencyPrices(
            eur = ath.eur,
            usd = ath.usd,
            aud = ath.aud,
            cad = ath.cad,
            chf = ath.chf,
            eth = ath.eth,
            gbp = ath.gbp,
            jpy = ath.jpy,
            mxn = ath.mxn,
            pln = ath.pln,
            rub = ath.rub,
            xag = ath.xag,
            xau = ath.xau,
            zar = ath.zar,
        ),
        priceChangePercentage1hInCurrency = CurrencyPrices(
            eur = priceChangePercentage1hInCurrency.eur,
            usd = priceChangePercentage1hInCurrency.usd,
            aud = priceChangePercentage1hInCurrency.aud,
            cad = priceChangePercentage1hInCurrency.cad,
            chf = priceChangePercentage1hInCurrency.chf,
            eth = priceChangePercentage1hInCurrency.eth,
            gbp = priceChangePercentage1hInCurrency.gbp,
            jpy = priceChangePercentage1hInCurrency.jpy,
            mxn = priceChangePercentage1hInCurrency.mxn,
            pln = priceChangePercentage1hInCurrency.pln,
            rub = priceChangePercentage1hInCurrency.rub,
            xag = priceChangePercentage1hInCurrency.xag,
            xau = priceChangePercentage1hInCurrency.xau,
            zar = priceChangePercentage1hInCurrency.zar,
        ),
        priceChangePercentage24hInCurrency = CurrencyPrices(
            eur = priceChangePercentage24hInCurrency.eur,
            usd = priceChangePercentage24hInCurrency.usd,
            aud = priceChangePercentage24hInCurrency.aud,
            cad = priceChangePercentage24hInCurrency.cad,
            chf = priceChangePercentage24hInCurrency.chf,
            eth = priceChangePercentage24hInCurrency.eth,
            gbp = priceChangePercentage24hInCurrency.gbp,
            jpy = priceChangePercentage24hInCurrency.jpy,
            mxn = priceChangePercentage24hInCurrency.mxn,
            pln = priceChangePercentage24hInCurrency.pln,
            rub = priceChangePercentage24hInCurrency.rub,
            xag = priceChangePercentage24hInCurrency.xag,
            xau = priceChangePercentage24hInCurrency.xau,
            zar = priceChangePercentage24hInCurrency.zar,
        ),
        priceChangePercentage7dInCurrency = CurrencyPrices(
            eur = priceChangePercentage7dInCurrency.eur,
            usd = priceChangePercentage7dInCurrency.usd,
            aud = priceChangePercentage7dInCurrency.aud,
            cad = priceChangePercentage7dInCurrency.cad,
            chf = priceChangePercentage7dInCurrency.chf,
            eth = priceChangePercentage7dInCurrency.eth,
            gbp = priceChangePercentage7dInCurrency.gbp,
            jpy = priceChangePercentage7dInCurrency.jpy,
            mxn = priceChangePercentage7dInCurrency.mxn,
            pln = priceChangePercentage7dInCurrency.pln,
            rub = priceChangePercentage7dInCurrency.rub,
            xag = priceChangePercentage7dInCurrency.xag,
            xau = priceChangePercentage7dInCurrency.xau,
            zar = priceChangePercentage7dInCurrency.zar,
        ),
        priceChangePercentage14dInCurrency = CurrencyPrices(
            eur = priceChangePercentage14dInCurrency.eur,
            usd = priceChangePercentage14dInCurrency.usd,
            aud = priceChangePercentage14dInCurrency.aud,
            cad = priceChangePercentage14dInCurrency.cad,
            chf = priceChangePercentage14dInCurrency.chf,
            eth = priceChangePercentage14dInCurrency.eth,
            gbp = priceChangePercentage14dInCurrency.gbp,
            jpy = priceChangePercentage14dInCurrency.jpy,
            mxn = priceChangePercentage14dInCurrency.mxn,
            pln = priceChangePercentage14dInCurrency.pln,
            rub = priceChangePercentage14dInCurrency.rub,
            xag = priceChangePercentage14dInCurrency.xag,
            xau = priceChangePercentage14dInCurrency.xau,
            zar = priceChangePercentage14dInCurrency.zar,
        ),
        priceChangePercentage30dInCurrency = CurrencyPrices(
            eur = priceChangePercentage30dInCurrency.eur,
            usd = priceChangePercentage30dInCurrency.usd,
            aud = priceChangePercentage30dInCurrency.aud,
            cad = priceChangePercentage30dInCurrency.cad,
            chf = priceChangePercentage30dInCurrency.chf,
            eth = priceChangePercentage30dInCurrency.eth,
            gbp = priceChangePercentage30dInCurrency.gbp,
            jpy = priceChangePercentage30dInCurrency.jpy,
            mxn = priceChangePercentage30dInCurrency.mxn,
            pln = priceChangePercentage30dInCurrency.pln,
            rub = priceChangePercentage30dInCurrency.rub,
            xag = priceChangePercentage30dInCurrency.xag,
            xau = priceChangePercentage30dInCurrency.xau,
            zar = priceChangePercentage30dInCurrency.zar,
        ),
        priceChangePercentage60dInCurrency = CurrencyPrices(
            eur = priceChangePercentage60dInCurrency.eur,
            usd = priceChangePercentage60dInCurrency.usd,
            aud = priceChangePercentage60dInCurrency.aud,
            cad = priceChangePercentage60dInCurrency.cad,
            chf = priceChangePercentage60dInCurrency.chf,
            eth = priceChangePercentage60dInCurrency.eth,
            gbp = priceChangePercentage60dInCurrency.gbp,
            jpy = priceChangePercentage60dInCurrency.jpy,
            mxn = priceChangePercentage60dInCurrency.mxn,
            pln = priceChangePercentage60dInCurrency.pln,
            rub = priceChangePercentage60dInCurrency.rub,
            xag = priceChangePercentage60dInCurrency.xag,
            xau = priceChangePercentage60dInCurrency.xau,
            zar = priceChangePercentage60dInCurrency.zar,
        ),
        priceChangePercentage200dInCurrency = CurrencyPrices(
            eur = priceChangePercentage200dInCurrency.eur,
            usd = priceChangePercentage200dInCurrency.usd,
            aud = priceChangePercentage200dInCurrency.aud,
            cad = priceChangePercentage200dInCurrency.cad,
            chf = priceChangePercentage200dInCurrency.chf,
            eth = priceChangePercentage200dInCurrency.eth,
            gbp = priceChangePercentage200dInCurrency.gbp,
            jpy = priceChangePercentage200dInCurrency.jpy,
            mxn = priceChangePercentage200dInCurrency.mxn,
            pln = priceChangePercentage200dInCurrency.pln,
            rub = priceChangePercentage200dInCurrency.rub,
            xag = priceChangePercentage200dInCurrency.xag,
            xau = priceChangePercentage200dInCurrency.xau,
            zar = priceChangePercentage200dInCurrency.zar,
        ),
        priceChangePercentage1yInCurrency = CurrencyPrices(
            eur = priceChangePercentage1yInCurrency.eur,
            usd = priceChangePercentage1yInCurrency.usd,
            aud = priceChangePercentage1yInCurrency.aud,
            cad = priceChangePercentage1yInCurrency.cad,
            chf = priceChangePercentage1yInCurrency.chf,
            eth = priceChangePercentage1yInCurrency.eth,
            gbp = priceChangePercentage1yInCurrency.gbp,
            jpy = priceChangePercentage1yInCurrency.jpy,
            mxn = priceChangePercentage1yInCurrency.mxn,
            pln = priceChangePercentage1yInCurrency.pln,
            rub = priceChangePercentage1yInCurrency.rub,
            xag = priceChangePercentage1yInCurrency.xag,
            xau = priceChangePercentage1yInCurrency.xau,
            zar = priceChangePercentage1yInCurrency.zar,
        ),
        marketCapChangePercentage24hInCurrency = CurrencyPrices(
            eur = marketCapChangePercentage24hInCurrency.eur,
            usd = marketCapChangePercentage24hInCurrency.usd,
            aud = marketCapChangePercentage24hInCurrency.aud,
            cad = marketCapChangePercentage24hInCurrency.cad,
            chf = marketCapChangePercentage24hInCurrency.chf,
            eth = marketCapChangePercentage24hInCurrency.eth,
            gbp = marketCapChangePercentage24hInCurrency.gbp,
            jpy = marketCapChangePercentage24hInCurrency.jpy,
            mxn = marketCapChangePercentage24hInCurrency.mxn,
            pln = marketCapChangePercentage24hInCurrency.pln,
            rub = marketCapChangePercentage24hInCurrency.rub,
            xag = marketCapChangePercentage24hInCurrency.xag,
            xau = marketCapChangePercentage24hInCurrency.xau,
            zar = marketCapChangePercentage24hInCurrency.zar,
        ),
        maxSupply = maxSupply,
        circulatingSupply = circulatingSupply,
    )